networkjournal/apps/home/urls.py
from  django.urls import  path
from django.views.generic import RedirectView

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('diary', views.diary, name='diary'),
    path('timetable', views.timetable, name='timetable'),
    path('notifications/', views.notifi, name='notifications'),

    path('marks/', views.staistic, name='statistic'),

    path('register/', views.director_register_menu, name='register_menu'),
    path('register/create/', views.create_director_user, name='create_director_user'),

    path('login/', views.SiteLoginView.as_view(), name='login_page'),
    path('logout/', views.SiteLogOut.as_view(), name='logout'),

    path('news/<int:article>/', views.det, name='det'),
    path('news/<int:article>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('news/', RedirectView.as_view(url='/', permanent=True)),

    path('profile/', views.profile, name='profile'),


    # for director
    path('news/edit/', views.edit_article_page, name='edit_article'),
    path('news/update/<int:id>', views.update_article_page, name='update_article'),
    path('news/delete/<int:id>', views.delete_article_page, name='delete_article'),

    path('school_setup/', views.school_setup, name='school_setup'),
    path('school_setup/add/', views.add_school, name='create_school'),
    path('school_setup/edit/', views.edit_school, name='edit_school'),


    path('school_setup/add_class/', views.add_school_class, name='create_class'),
    path('school_setup/edit_class/<int:id>', views.edit_school_class, name='redact_class'),
    path('school_setup/delete_class/<int:id>', views.delete_school_class, name='delete_class'),

    path('school_setup/add_classmate/<int:id>', views.add_classmate_to_class, name='add_classmate'),
    path('school_setup/edit_child/<int:id>', views.edit_child, name='redact_classmate'),
    path('school_setup/delete_child/<int:id>', views.delete_child, name='delete_classmate'),

    path('school_setup/add_teacher/', views.add_teacher, name='add_teacher'),
    path('school_setup/edit_teacher/<int:id>', views.edit_teacher, name='edit_teacher'),
    path('school_setup/delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),

    path('school_setup/edit_timetable/<int:id>', views.edit_timetable, name='redact_timetable'),

    path('school_setup/add_subject/', views.add_subject, name='add_subject'),

    path('school_setup/edit_subject/<int:id>', views.edit_subject, name='edit_subject'),
    path('school_setup/delete_subject/<int:id>', views.delete_subject, name='delete_subject'),

    #path('school_setup/add_subject_to_day/<int:id>', views.add_subject_to_day, name='add_subject_to_day'),

    path('school_setup/edit_daysubject/<int:id>', views.edit_subject_in_day, name='edit_daysubject'),

    path('my_class', views.my_class, name='my_class'),

    path('teach', views.teach, name="teach_"),
    path('teach/<int:id>/<int:sub>', views.teach_det, name="teach"),

    path('leave_mark/<int:year>/<int:month>/<int:day>/<int:id>/<int:subj>/<int:i>', views.leave_mark, name="leave_mark"),

    path('edit_mark/<int:year>/<int:month>/<int:day>/<int:id>/<int:subj>/<int:i>', views.edit_mark, name="edit_mark"),

    path('teach/edit_hw/<int:id>', views.edit_hw, name="edit_hw"),
    path('teach/delete_hw/<int:id>', views.delete_hw, name="delete_hw")
]

networkjournal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('', include('home.urls')),
    #path('', RedirectView.as_view(url='/child/', permanent=True)),
    #path('home/', RedirectView.as_view(url='/child/', permanent=True)),
]

networkjournal/apps/home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from .models import Article, School, Class

class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

networkjournal/apps/home/views.py
from django.core.checks import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from datetime import  date

from .models import *
from django.contrib.auth.views import LoginView, LogoutView
from .forms import AuthUserForm, ArticleForm

from .user_fields import *

from django.contrib.auth.models import User


def index(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')

        try:
            sc = School.objects.get(id=get_user_school(request.user))
        #a = Article.objects.get(school=sc).order_by('-date')
        except:
            return HttpResponseRedirect(reverse('home:school_setup'))
        a = sc.article_set.order_by('-date')
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        if get_user_status(request.user) == 'director':
            return render(request, 'director/list.html', {'article': a, 'username': username})
        elif get_user_status(request.user) == 'teacher':
            return render(request, 'teacher/list.html', {'article': a, 'username': username})
        else:
            return render(request, 'child/list.html', {'article': a, 'username': username})


def profile(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        profile = request.user
        r_username = get_user_name(request.user)
        r_usersurname = get_user_surname(request.user)
        r_userfathername = get_user_fathername(request.user)
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        if get_user_status(request.user) == 'director':
            r_userrole = 'директор / системный администратор'
            return render(request, 'director/profile.html',
                          {'profile': profile, 'username': username, 'role': r_userrole, 'name': r_username,
                           'surname': r_usersurname, 'fathername': r_userfathername})
        elif get_user_status(request.user) == 'teacher':
            r_userrole = 'учитель'
            return render(request, 'teacher/profile.html',
                          {'profile': profile, 'username': username, 'role': r_userrole, 'name': r_username,
                           'surname': r_usersurname, 'fathername': r_userfathername})
        else:
            r_userrole = 'ученик'
            return render(request, 'child/profile.html',
                          {'profile': profile, 'username': username, 'role': r_userrole, 'name': r_username,
                           'surname': r_usersurname, 'fathername': r_userfathername})


def notifi(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        a = Article.objects.order_by('-date')[:5]
        # return render(request, 'home/notifi.html', {'notifications': a})
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        if get_user_status(request.user) == 'director':
            return render(request, 'director/notifi.html', {'username': username})
        else:
            return render(request, 'child/notifi.html', {'username': username})


def timetable(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        cl = Class.objects.get(pk=get_user_class(request.user))
        t = cl.timetable_set.get()

        days = ['Понедельник', 'Вторник', 'Среда', 'Черверг', 'Пятница', 'Суббота', 'Воскресенье']

        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        context = {
            'username': username,
            'class': cl,
            'timetable': t,
            'today': days[datetime.date.today().weekday()],
            'time': (timezone.now() + datetime.timedelta(hours=7)).time()
        }
        return render(request, 'child/timetable.html', context)


def det(request, article):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        try:
            a = Article.objects.get(id=article)
        except:
            raise Http404('Такой статьи не существует')

        latest_comm_list = a.comment_set.order_by('-id')[:10]
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)

        if get_user_status(request.user) == 'director':
            return render(request, 'director/det.html',
                          {'article': a, 'latest_comm_list': latest_comm_list, 'username': username})
        elif get_user_status(request.user) == 'teacher':
            return render(request, 'teacher/det.html',
                          {'article': a, 'latest_comm_list': latest_comm_list, 'username': username})
        else:
            return render(request, 'child/det.html',
                          {'article': a, 'latest_comm_list': latest_comm_list, 'username': username})


def leave_comment(request, article):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        try:
            a = Article.objects.get(id=article)
        except:
            raise Http404('Такой статьи не существует')

        a.comment_set.create(author=get_user_name(request.user) + ' ' + get_user_surname(request.user),
                             text=request.POST['text'])

        return HttpResponseRedirect(reverse('home:det', args=(a.id,)))


def director_register_menu(request):
    return render(request, 'register/director_register.html')


def create_director_user(request):
    userName = request.POST['userName']

    userRealName = request.POST['userRealName']
    userLastName = request.POST['userLastName']
    userFatherName = request.POST['userFatherName']

    userEmail = request.POST['inputEmail']

    userPassword = request.POST['inputPassword']
    userPasswordReq = request.POST['inputPasswordReq']
    if userPassword == userPasswordReq:
        newUser = User.objects.create_user(userName, userEmail, userPassword)
        newUser.last_name = 'director___' + userRealName + '___' + userLastName + '___' + userFatherName + '___schoolid=0'
        newUser.save()
        return HttpResponseRedirect(reverse('home:login_page'))


def edit_article_page(request):
    if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
    if get_user_status(request.user) == 'director':
        success = False
        try:
            sc = School.objects.get(director=request.user)
        except:
            return HttpResponseRedirect(reverse('home:school_setup'))
        if request.method == 'POST':
            title = request.POST['title']
            text = request.POST['text']
            sc.article_set.create(title=title, text=text)
            sc.save()
            return HttpResponseRedirect(reverse('home:edit_article'))

        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        template = 'director/edit_page.html'
        context = {
            'list_articles': sc.article_set.all(),
            'username': username,
            'success': success
        }
        return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse('home:edit_article'))


def update_article_page(request, id):
    if get_user_status(request.user) == 'director':
        a = Article.objects.get(pk=id)
        if request.method == 'POST':
            title = request.POST['title']
            text = request.POST['text']
            a.title = title
            a.text = text
            a.save()
            return HttpResponseRedirect(reverse('home:edit_article'))

        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        template = 'director/edit_page.html'
        context = {
            'get_article': a,
            'update': True,
            'username': username,
            'req_title': a.title,
            'req_text': a.text
        }

        return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse('home:edit_article'))


def delete_article_page(request, id):
    a = Article.objects.get(pk=id)
    a.delete()
    return HttpResponseRedirect(reverse('home:edit_article'))

class SiteLoginView(LoginView):
    template_name = 'user_login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('home:index')

    def get_success_url(self):
        return self.success_url


class SiteLogOut(LogoutView):
    next_page = reverse_lazy('home:login_page')


def diary(request):
    if get_user_status(request.user) == 'child':
        cl = Class.objects.get(pk=get_user_class(request.user))
        ttable = cl.timetable_set.get(schoolClass=cl)

        current_week = date.today().isocalendar()[1]

        monday = ttable.dayofweek_set.get(dayname='Понедельник')
        tuesday = ttable.dayofweek_set.get(dayname='Вторник')
        wednesday = ttable.dayofweek_set.get(dayname='Среда')
        thurthday = ttable.dayofweek_set.get(dayname='Четверг')
        friday = ttable.dayofweek_set.get(dayname='Пятница')
        saturday = ttable.dayofweek_set.get(dayname='Суббота')

        # get subjects

networkjournal/templates/director/add_article.html
{% extends 'director_base.html' %}

{% block title %}Добавление новости{% endblock %}
{% block content %}

 <div class="container">
	<form action="{% url 'home:leave_article' article.id %}" method="post">
    {% csrf_token %}
		<input class="form-control" name="title" required placeholder="Заголовок"></input>
		<textarea class="form-control" name="text" required placeholder="Текст новости"></textarea>
    <button class="btn btn-info" type="submit" name="button">Опубликовать новость</button>
  </form>
 </div>
{% endblock %}

networkjournal/templates/director/add_subject.html
{% extends 'director_base.html' %}
{% block title %}Настройки школы{% endblock %}
{% block content %}
<div class="container text-center">
  <h6>Добавление школьного предмета</h6>
  <form id="form" method="post">
    {% csrf_token %}
    <input class="form-control" type="text" name="m_name" required placeholder="Наименование школьного предмета" value="">
  </form>
  <button form="form" class="btn btn-success" type="submit" name="button">Добавить</button>
  <a href="#" class="btn btn-outline-success" >Отмена</a>
</div>
{% endblock %}

networkjournal/templates/director/add_subject_to_day.html
{% extends 'director_base.html' %}
{% block title %}Настройки школы{% endblock %}
{% block content %}
<form id="form" method="post">
  <select class="form-control" name="subject">
    {% for s in subjects %}
      <option value="{{s.id}}">{{s}}</option>
    {% endfor %}
  </select>
</form>
{% endblock %}

networkjournal/templates/director/det.html
{% extends 'director_base.html' %}

{% block title %}{{article.title}} | Новости{% endblock %}
{% block content %}

<div class="container">
	<h3>{{article.title}}</h3>
	<hr>
	<p>{{article.text}}</p>
	<hr>
	<em>Опубликовано {{article.date}}</em>
	<!--<br>
	<br>
	<hr>
	<form action="{% url 'home:leave_comment' article.id %}" method="POST">

		{% csrf_token %}
		<input class="form-control" name="text" required placeholder="Текст комментария"></input>
		<button class="btn btn-info" type="submit" name="button">Оставить комментарий</button>
		<hr>
	</form>
	{% if latest_comm_list %}
	<h4>Комментарии пользователей</h4>
	<hr>
	<div class="container">
		{% for c in latest_comm_list %}
		<h4><strong>{{c.author}}</strong></h4>
		<h6>{{c.text}}</h6>
		<br>
		{% endfor %}
	</div>

	{% else %}
	<h5>Никто ещё не прокомментировал эту новость.</h5>
	{% endif %}-->
</div>
{% endblock %}

networkjournal/templates/director/edit_page.html
{% extends 'director_base.html' %}

{% block title %}Новости{% endblock %}
{% block content %}
<div class="container">
  <h4>Редактирование новостей</h4>
  {% if success %}
  <p style='color:green'>Новость успешно добавлена!</p>
  {% endif %}
  {% if update %}
    <form class="" id="update_form" method="post">
      {% csrf_token %}
      <input class="form-control" value="{{req_title}}" name="title" required placeholder="Заголовок"></input>
      <textarea class="form-control" name="text" required placeholder="Текст новости">{{req_text}}</textarea>
    </form>
    <button form="update_form" type="submit" class="btn btn-success">Применить изменения</button>
  {% else %}
    <br>
      <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
      Добавить новость
    </button>
    <br>
    <br>
  {% endif %}
  {% if list_articles %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Код</th>
        <th scope="col">Название</th>
        <th scope="col">Дата написания</th>
        <th scope="col">Редактирование</th>
        <th scope="col">Удаление</th>
      </tr>
    </thead>
    <tbody>
      {% for a in list_articles %}
        <tr>
          <th>{{a.id}}</th>
          <td>{{a.title}}</td>
          <td>{{a.date}}</td>
          <td><a href="{% url 'home:update_article' a.id %}">Редактировать</a></td>
          <td><a href="{% url 'home:delete_article' a.id %}">Удалить</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  {% endif %}


  <!-- Modal -->
  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Добавление новости</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form class="" id="add_form" method="post">
            {% csrf_token %}
        		<input class="form-control" name="title" required placeholder="Заголовок"></input>
        		<textarea class="form-control" name="text" required placeholder="Текст новости"></textarea>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
          <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

networkjournal/templates/director/edit_school_main.html
{% extends 'director_base.html' %}
{% block title %}Настройки школы{% endblock %}
{% block content %}
<div class="container text-center">
  <form class="" id="ed_form" method="post">
    {% csrf_token %}
    <input class="form-control" type="text" name="name" value="{{req_name}}"   required placeholder="Название">
    <input class="form-control" type="url" name="site" value="{{req_site}}" placeholder="Сайт">
  </form>
  <button form="ed_form" type="submit" class="btn btn-success">Применить</button>
</div>
{% endblock %}

networkjournal/templates/director/notifi.html
{% extends 'director_base.html' %}

{% block title %}Новости{% endblock %}
{% block content %}
{% if article %}
<div class="container">
 <hr>
 <strong>Новости</strong>
 <br>
	{% for a in article %}
		<a class="btn btn-info btn-sm" href="{% url 'home:det' a.id %}">{{a.title}}</a>
		<br>
		<br>
	{% endfor %}

	 </div>
{% else %}
{% endif %}
{% endblock %}

networkjournal/templates/director/school_setup.html
{% extends 'director_base.html' %}
{% block title %}Настройки школы{% endblock %}
{% block content %}
<div class="container">
  {% if addclass %}
    <form class="" id="add_cl_form" method="post">
      {% csrf_token %}
      <input name="cl_num" type="number" class="form-control" placeholder="Цифра класса" min="1" max="11" maxlength="1" required autofocus>
      <input name="cl_letter" class="form-control" placeholder="Буква класса" maxlength="1" required autofocus>
      <label for="sel_teach">Выберите классного руководителя</label>
          <select name="teach" id="sel_teach">
            {% for t, nm in teachers_list %}
            <option value="{{t.id}}">{{t}} ({{nm}})</option>
            {% endfor %}
          </select>
    </form>
    <a href="/school_setup/" class="btn btn-secondary">Отмена</a>
    <button form="add_cl_form" type="submit" class="btn btn-primary">Добавить класс</button>
  {% else %}
    {% if editclass %}
      {% if addclassmate %}
        <form class="" id="ed_childs_form" method="post">
          {% csrf_token %}
          <input class="form-control" type="text" name="name"  required placeholder="Имя">
          <input class="form-control" type="text" name="surname"  required placeholder="Фамилия">
          <input class="form-control" type="text" name="fathername"  required placeholder="Отчество">
          <br>
          <input class="form-control" type="text" name="username"  required placeholder="Имя пользователя">
          <input class="form-control" type="password" name="password"  required placeholder="Пароль">
        </form>
        <button form="ed_childs_form" type="submit" class="btn btn-success">Добавить</button>
      {% else %}
        <form class="" id="ed_cl_form" method="post">
          {% csrf_token %}
          <input name="cl_num" type="number" class="form-control" value="{{req_num}}" placeholder="Цифра класса" min="1" max="11" maxlength="1" required autofocus>
          <input name="cl_letter" class="form-control" placeholder="Буква класса" value="{{req_char}}" maxlength="1" required autofocus>
          <label for="sel_teach">Выберите классного руководителя</label>
          <select name="teach" id="sel_teach">
            {% for t, nm, d in teachers_list %}
            <option {% if d %}selected{% endif %} value="{{t.id}}">{{t}} ({{nm}})</option>
            {% endfor %}
          </select>
        </form>
        <button form="ed_cl_form" type="submit" class="btn btn-success">Применить изменения</button>
        <hr>
        {% if classmates %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Логин</th>
                <th scope="col">Ф.И.О</th>
                <th scope="col">Редактирование</th>
                <th scope="col">Удаление</th>
              </tr>
            </thead>
            <tbody>
              {% for usr, fio in classmates %}
                <tr>
                  <th>{{usr}}</th>
                  <td>{{fio}}</td>
                  <td><a href="{% url 'home:redact_classmate' usr.id %}">Редактировать</a></td>
                  <td><a href="{% url 'home:delete_classmate' usr.id %}">Удалить</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
        <a href="{% url 'home:add_classmate' classid %}" class="btn btn-outline-primary">Добавить ученика в этот класс</a>
        <hr>
        <a class="btn btn-primary" href="{% url 'home:redact_timetable' classid %}">Настройка расписания</a>
        <hr>
        <a href="/school_setup/" class="btn btn-outline-success">Назад</a>
      {% endif %}
    {% else %}
      {% if school %}
      <div class="container text-center">
        <span><strong style="color:green; font-size: 22pt;">{{ school.name }}</strong><a href="{% url 'home:edit_school' %}" class="btn btn-light btn-sm">✏</a></span>
        <br>
        <br>
        {% if classes %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Класс</th>
              <th scope="col">Редактирование</th>
              <th scope="col">Удаление</th>
            </tr>
          </thead>
          <tbody>
            {% for c in classes %}
              <tr>
                <td>{{c}}</td>
                <td><a href="{% url 'home:redact_class' c.id %}">Редактировать</a></td>
                <td><a href="{% url 'home:delete_class' c.id %}">Удалить</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
          <h2>Вы ещё не добавили ни одного класса.</h2>
        {% endif %}
        <a class="btn btn-outline-primary" href="/school_setup/add_class/">Добавить класс</a>
        <br>
        <hr>
        <h3>Учителя</h3>
        {% if teachers %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Логин</th>
                <th scope="col">Ф.И.О</th>
                <th scope="col">Редактирование</th>
                <th scope="col">Удаление</th>
              </tr>
            </thead>
            <tbody>
              {% for usr, fio in teachers %}
                <tr>
                  <th>{{usr}}</th>
                  <td>{{fio}}</td>
                  <td><a href="{% url 'home:edit_teacher' usr.id %}">Редактировать</a></td>
                  <td><a href="{% url 'home:delete_teacher' usr.id %}">Удалить</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
        <a class="btn btn-outline-primary" href="/school_setup/add_teacher/">Добавить учителя</a>
        <br>
        <hr>
        <h3>Предметы</h3>
        {% if subjects %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Название</th>
                <th scope="col">Редактирование</th>
                <th scope="col">Удаление</th>
              </tr>
            </thead>
            <tbody>
              {% for n in subjects %}
                <tr>
                  <th>{{n}}</th>
                  <td><a href="{% url 'home:edit_subject' n.id %}">Редактировать</a></td>
                  <td><a href="{% url 'home:delete_subject' n.id %}">Удалить</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
        <a class="btn btn-outline-primary" href="/school_setup/add_subject/">Добавить предмет</a>
      </div>
      {% else %}
        <h2>Сначала добавьте школу.</h2>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">Добавить школу</button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Добавление школы</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form class="" id="add_sc_form" method="post">
                  {% csrf_token %}
                  <!--{{ form }}-->
                  <input name="sc_name" class="form-control" placeholder="Название учебного заведения" maxlength="50" required autofocus>
                  <input class="form-control" type="url" placeholder="Сайт учебного заведения" name="sc_site">
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                <button form="add_sc_form" type="submit" class="btn btn-primary">Добавить школу</button>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endif %}
  {% endif %}
</div>
{% endblock %}

networkjournal/templates/director/timetable.html
{% extends 'director_base.html' %}
{% block title %}Настройки школы{% endblock %}
{% block content %}
<div class="container text-center">
  <h1>Расписание</h1>  <span><a href="/school_setup/edit_class/{{id}}">вернуться назад</a></span>
  {% for d, v in days %}
    <h4>{{d}}</h4>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Предмет</th>
          <th scope="col">Преподаватель</th>
          <th scope="col">Время начала</th>
          <th scope="col">Время конца</th>
          <th scope="col">Редактирование</th>
        </tr>
      </thead>
      <tbody>
        {% for subj in v %}
        <tr>
          <th scope="row">{{subj.sublocalid}}</th>
          <td scope="row">{{subj.get_subject_model}}</td>
          <td scope="row">{{subj.get_teacher_model}} {{subj.get_teacher_name_and_surname_brackets}}</td>
          <td scope="row">{{subj.timeOfStart}}</td>
          <td scope="row">{{subj.timeOfEnd}}</td>
          <td scope="row"><a href="{% url 'home:edit_daysubject' subj.id %}" class="btn btn-sm btn-outline-primary">Редактирование</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br>
    <br>
  {% endfor %}
</div>
{% endblock %}