networkjournal/apps/home/urls.py
from  django.urls import  path
from django.views.generic import RedirectView

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('diary', views.diary, name='diary'),
    path('timetable', views.timetable, name='timetable'),
    path('notifications/', views.notifi, name='notifications'),

    path('marks/', views.staistic, name='statistic'),

    path('register/', views.director_register_menu, name='register_menu'),
    path('register/create/', views.create_director_user, name='create_director_user'),

    path('login/', views.SiteLoginView.as_view(), name='login_page'),
    path('logout/', views.SiteLogOut.as_view(), name='logout'),

    path('news/<int:article>/', views.det, name='det'),
    path('news/<int:article>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('news/', RedirectView.as_view(url='/', permanent=True)),

    path('profile/', views.profile, name='profile'),


    # for director
    path('news/edit/', views.edit_article_page, name='edit_article'),
    path('news/update/<int:id>', views.update_article_page, name='update_article'),
    path('news/delete/<int:id>', views.delete_article_page, name='delete_article'),

    path('school_setup/', views.school_setup, name='school_setup'),
    path('school_setup/add/', views.add_school, name='create_school'),
    path('school_setup/edit/', views.edit_school, name='edit_school'),


    path('school_setup/add_class/', views.add_school_class, name='create_class'),
    path('school_setup/edit_class/<int:id>', views.edit_school_class, name='redact_class'),
    path('school_setup/delete_class/<int:id>', views.delete_school_class, name='delete_class'),

    path('school_setup/add_classmate/<int:id>', views.add_classmate_to_class, name='add_classmate'),
    path('school_setup/edit_child/<int:id>', views.edit_child, name='redact_classmate'),
    path('school_setup/delete_child/<int:id>', views.delete_child, name='delete_classmate'),

    path('school_setup/add_teacher/', views.add_teacher, name='add_teacher'),
    path('school_setup/edit_teacher/<int:id>', views.edit_teacher, name='edit_teacher'),
    path('school_setup/delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),

    path('school_setup/edit_timetable/<int:id>', views.edit_timetable, name='redact_timetable'),

    path('school_setup/add_subject/', views.add_subject, name='add_subject'),

    path('school_setup/edit_subject/<int:id>', views.edit_subject, name='edit_subject'),
    path('school_setup/delete_subject/<int:id>', views.delete_subject, name='delete_subject'),

    #path('school_setup/add_subject_to_day/<int:id>', views.add_subject_to_day, name='add_subject_to_day'),

    path('school_setup/edit_daysubject/<int:id>', views.edit_subject_in_day, name='edit_daysubject'),

    path('my_class', views.my_class, name='my_class'),

    path('teach', views.teach, name="teach_"),
    path('teach/<int:id>/<int:sub>', views.teach_det, name="teach"),

    path('leave_mark/<int:year>/<int:month>/<int:day>/<int:id>/<int:subj>/<int:i>', views.leave_mark, name="leave_mark"),

    path('edit_mark/<int:year>/<int:month>/<int:day>/<int:id>/<int:subj>/<int:i>', views.edit_mark, name="edit_mark"),

    path('teach/edit_hw/<int:id>', views.edit_hw, name="edit_hw"),
    path('teach/delete_hw/<int:id>', views.delete_hw, name="delete_hw")
]

networkjournal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('', include('home.urls')),
    #path('', RedirectView.as_view(url='/child/', permanent=True)),
    #path('home/', RedirectView.as_view(url='/child/', permanent=True)),
]

networkjournal/apps/home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from .models import Article, School, Class

class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

networkjournal/apps/home/views.py
from django.core.checks import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from datetime import  date

from .models import *
from django.contrib.auth.views import LoginView, LogoutView
from .forms import AuthUserForm, ArticleForm

from .user_fields import *

from django.contrib.auth.models import User


def index(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')

        try:
            sc = School.objects.get(id=get_user_school(request.user))
        #a = Article.objects.get(school=sc).order_by('-date')
        except:
            return HttpResponseRedirect(reverse('home:school_setup'))
        a = sc.article_set.order_by('-date')
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        if get_user_status(request.user) == 'director':
            return render(request, 'director/list.html', {'article': a, 'username': username})
        elif get_user_status(request.user) == 'teacher':
            return render(request, 'teacher/list.html', {'article': a, 'username': username})
        else:
            return render(request, 'child/list.html', {'article': a, 'username': username})


def profile(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        profile = request.user
        r_username = get_user_name(request.user)
        r_usersurname = get_user_surname(request.user)
        r_userfathername = get_user_fathername(request.user)
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        if get_user_status(request.user) == 'director':
            r_userrole = 'директор / системный администратор'
            return render(request, 'director/profile.html',
                          {'profile': profile, 'username': username, 'role': r_userrole, 'name': r_username,
                           'surname': r_usersurname, 'fathername': r_userfathername})
        elif get_user_status(request.user) == 'teacher':
            r_userrole = 'учитель'
            return render(request, 'teacher/profile.html',
                          {'profile': profile, 'username': username, 'role': r_userrole, 'name': r_username,
                           'surname': r_usersurname, 'fathername': r_userfathername})
        else:
            r_userrole = 'ученик'
            return render(request, 'child/profile.html',
                          {'profile': profile, 'username': username, 'role': r_userrole, 'name': r_username,
                           'surname': r_usersurname, 'fathername': r_userfathername})


def notifi(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        a = Article.objects.order_by('-date')[:5]
        # return render(request, 'home/notifi.html', {'notifications': a})
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        if get_user_status(request.user) == 'director':
            return render(request, 'director/notifi.html', {'username': username})
        else:
            return render(request, 'child/notifi.html', {'username': username})


def timetable(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        cl = Class.objects.get(pk=get_user_class(request.user))
        t = cl.timetable_set.get()

        days = ['Понедельник', 'Вторник', 'Среда', 'Черверг', 'Пятница', 'Суббота', 'Воскресенье']

        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        context = {
            'username': username,
            'class': cl,
            'timetable': t,
            'today': days[datetime.date.today().weekday()],
            'time': (timezone.now() + datetime.timedelta(hours=7)).time()
        }
        return render(request, 'child/timetable.html', context)


def det(request, article):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        try:
            a = Article.objects.get(id=article)
        except:
            raise Http404('Такой статьи не существует')

        latest_comm_list = a.comment_set.order_by('-id')[:10]
        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)

        if get_user_status(request.user) == 'director':
            return render(request, 'director/det.html',
                          {'article': a, 'latest_comm_list': latest_comm_list, 'username': username})
        elif get_user_status(request.user) == 'teacher':
            return render(request, 'teacher/det.html',
                          {'article': a, 'latest_comm_list': latest_comm_list, 'username': username})
        else:
            return render(request, 'child/det.html',
                          {'article': a, 'latest_comm_list': latest_comm_list, 'username': username})


def leave_comment(request, article):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse('home:login_page'))
    else:
        if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
        try:
            a = Article.objects.get(id=article)
        except:
            raise Http404('Такой статьи не существует')

        a.comment_set.create(author=get_user_name(request.user) + ' ' + get_user_surname(request.user),
                             text=request.POST['text'])

        return HttpResponseRedirect(reverse('home:det', args=(a.id,)))


def director_register_menu(request):
    return render(request, 'register/director_register.html')


def create_director_user(request):
    userName = request.POST['userName']

    userRealName = request.POST['userRealName']
    userLastName = request.POST['userLastName']
    userFatherName = request.POST['userFatherName']

    userEmail = request.POST['inputEmail']

    userPassword = request.POST['inputPassword']
    userPasswordReq = request.POST['inputPasswordReq']
    if userPassword == userPasswordReq:
        newUser = User.objects.create_user(userName, userEmail, userPassword)
        newUser.last_name = 'director___' + userRealName + '___' + userLastName + '___' + userFatherName + '___schoolid=0'
        newUser.save()
        return HttpResponseRedirect(reverse('home:login_page'))


def edit_article_page(request):
    if get_user_status(request.user) == '0': return HttpResponseRedirect('/admin/')
    if get_user_status(request.user) == 'director':
        success = False
        try:
            sc = School.objects.get(director=request.user)
        except:
            return HttpResponseRedirect(reverse('home:school_setup'))
        if request.method == 'POST':
            title = request.POST['title']
            text = request.POST['text']
            sc.article_set.create(title=title, text=text)
            sc.save()
            return HttpResponseRedirect(reverse('home:edit_article'))

        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        template = 'director/edit_page.html'
        context = {
            'list_articles': sc.article_set.all(),
            'username': username,
            'success': success
        }
        return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse('home:edit_article'))


def update_article_page(request, id):
    if get_user_status(request.user) == 'director':
        a = Article.objects.get(pk=id)
        if request.method == 'POST':
            title = request.POST['title']
            text = request.POST['text']
            a.title = title
            a.text = text
            a.save()
            return HttpResponseRedirect(reverse('home:edit_article'))

        username = get_user_name(request.user) + ' ' + get_user_surname(request.user)
        template = 'director/edit_page.html'
        context = {
            'get_article': a,
            'update': True,
            'username': username,
            'req_title': a.title,
            'req_text': a.text
        }

        return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse('home:edit_article'))


def delete_article_page(request, id):
    a = Article.objects.get(pk=id)
    a.delete()
    return HttpResponseRedirect(reverse('home:edit_article'))

class SiteLoginView(LoginView):
    template_name = 'user_login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('home:index')

    def get_success_url(self):
        return self.success_url


class SiteLogOut(LogoutView):
    next_page = reverse_lazy('home:login_page')


def diary(request):
    if get_user_status(request.user) == 'child':
        cl = Class.objects.get(pk=get_user_class(request.user))
        ttable = cl.timetable_set.get(schoolClass=cl)

        current_week = date.today().isocalendar()[1]

        monday = ttable.dayofweek_set.get(dayname='Понедельник')
        tuesday = ttable.dayofweek_set.get(dayname='Вторник')
        wednesday = ttable.dayofweek_set.get(dayname='Среда')
        thurthday = ttable.dayofweek_set.get(dayname='Четверг')
        friday = ttable.dayofweek_set.get(dayname='Пятница')
        saturday = ttable.dayofweek_set.get(dayname='Суббота')

        # get subjects

networkjournal/templates/register/director_register.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://lh3.googleusercontent.com/JPm2p8jOgxwShKIs02V3GBJsmQa0HwLpt1IIwzUxfrvjOgvm6UPfVcs52m64iX-lZzVTu47B6amWofzWPz2kznMXNbzIH7PhlnY6afdGZSgnHg-dTD8fuRvdUuTuVCVbmkYs_kYk_5_qtSRNki_SEAz9uD8N9Ngk2Jw7KMlxcTL5o3oSRV1cBBCOskoGtti1owcPFvsWRsQixTWqjohOXZ9j6RldsXgXQojDvZ4f87JSGNv6sb8K6KyxVqSgYYXiLEHMxx6i1p_M1lhf79IHST9jnWdPBnH8QRFQuyzdheAbA90uliJF614ybwYKmR3ku2aflAz043Z3x4E1O0hRW1Pe6-Zn4uvqp3SSfRIm8se3U2EvhYBKQ_lhi2O-2aW--TeeGqLT-GxNP4mUAqc3PG1nGyc6dVbLT8tPH0b2eeSiAgdsp-JSiaHb4rkj_zmAdyqnZsxiQn2ZKEVKHimS0AYNPWrYJucJUspYNWmpR0qcLSomappWEo1tbjXClu5XFLA_Ekf50Hd5bhMcFDg1dv7YV1pMgbzE1b5Uc8e9V_uPqppmeDhku8FDFylGhNrltrN9K5jP8UeT9UjWTvnUcmIOr-APDr3giy1yuhqmSENm9sMYa2RG7i1XOSO7xBphldVa8exbDUeSWL89sWCgaELRExeytDWTy2GqgVqHswN7QJ11xk2vau4LxeQcSW0=w200-h190-p-k-nu-ft">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Регистрация директора | Дневник</title>
  </head>
  <body class="text-center">
    {% csrf_token %}
    <div class="container">
    <form action="{% url 'home:create_director_user' %}" method="POST">
      {% csrf_token %}
      <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
      <br>
      <h6>Регистрация предназначена для директора либо системного администратора школы. Если вы - ученик, обратитесь в школу за паролем.</h6>
      <br>
      <input name="userName" class="form-control" placeholder="Имя пользователя" required autofocus>
      <br>
      <input name="userRealName" class="form-control" placeholder="Имя" required autofocus>
      <input name="userLastName" class="form-control" placeholder="Фамилия" required autofocus>
      <input name="userFatherName" class="form-control" placeholder="Отчество" required autofocus>
      <br>
      <input type="email" name="inputEmail" class="form-control" placeholder="Адрес электронной почты" required autofocus>
      <br>
      <input type="password" name="inputPassword" class="form-control" placeholder="Пароль" required>
      <input type="password" name="inputPasswordReq" class="form-control" placeholder="Повторите пароль" required>
      <br>
      <hr>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2019-2020 <a href="/login/">Назад</a></p>
    </form>
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

networkjournal/templates/register/teacher_register.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://lh3.googleusercontent.com/JPm2p8jOgxwShKIs02V3GBJsmQa0HwLpt1IIwzUxfrvjOgvm6UPfVcs52m64iX-lZzVTu47B6amWofzWPz2kznMXNbzIH7PhlnY6afdGZSgnHg-dTD8fuRvdUuTuVCVbmkYs_kYk_5_qtSRNki_SEAz9uD8N9Ngk2Jw7KMlxcTL5o3oSRV1cBBCOskoGtti1owcPFvsWRsQixTWqjohOXZ9j6RldsXgXQojDvZ4f87JSGNv6sb8K6KyxVqSgYYXiLEHMxx6i1p_M1lhf79IHST9jnWdPBnH8QRFQuyzdheAbA90uliJF614ybwYKmR3ku2aflAz043Z3x4E1O0hRW1Pe6-Zn4uvqp3SSfRIm8se3U2EvhYBKQ_lhi2O-2aW--TeeGqLT-GxNP4mUAqc3PG1nGyc6dVbLT8tPH0b2eeSiAgdsp-JSiaHb4rkj_zmAdyqnZsxiQn2ZKEVKHimS0AYNPWrYJucJUspYNWmpR0qcLSomappWEo1tbjXClu5XFLA_Ekf50Hd5bhMcFDg1dv7YV1pMgbzE1b5Uc8e9V_uPqppmeDhku8FDFylGhNrltrN9K5jP8UeT9UjWTvnUcmIOr-APDr3giy1yuhqmSENm9sMYa2RG7i1XOSO7xBphldVa8exbDUeSWL89sWCgaELRExeytDWTy2GqgVqHswN7QJ11xk2vau4LxeQcSW0=w200-h190-p-k-nu-ft">
    <title>Регистрация учителя | Дневник</title>
  </head>
  <body class="text-center">
    <div class="container">
    <form id="_form" method="POST">
      {% csrf_token %}
      <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Регистрация нового учителя</h1>
      <br>
      <input name="username" class="form-control" placeholder="Имя пользователя" required autofocus>
      <br>
      <input name="name" class="form-control" placeholder="Имя" required autofocus>
      <input name="surname" class="form-control" placeholder="Фамилия" required autofocus>
      <input name="fathername" class="form-control" placeholder="Отчество" required autofocus>
      <br>
      <input type="password" name="password" class="form-control" placeholder="Пароль" required>
      <br>
      <hr>
      <button class="btn btn-lg btn-primary btn-block" form="_form" type="submit">Зарегистрировать учителя</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2019-2020 <a href="/login/">Авторизация</a></p>
    </form>
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>