networkjournal/apps/home/urls.py
from  django.urls import  path
from django.views.generic import RedirectView

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('diary', views.diary, name='diary'),
    path('timetable', views.timetable, name='timetable'),
    path('notifications/', views.notifi, name='notifications'),

    path('marks/', views.staistic, name='statistic'),

    path('register/', views.director_register_menu, name='register_menu'),
    path('register/create/', views.create_director_user, name='create_director_user'),

    path('login/', views.SiteLoginView.as_view(), name='login_page'),
    path('logout/', views.SiteLogOut.as_view(), name='logout'),

    path('news/<int:article>/', views.det, name='det'),
    path('news/<int:article>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('news/', RedirectView.as_view(url='/', permanent=True)),

    path('profile/', views.profile, name='profile'),


    # for director
    path('news/edit/', views.edit_article_page, name='edit_article'),
    path('news/update/<int:id>', views.update_article_page, name='update_article'),
    path('news/delete/<int:id>', views.delete_article_page, name='delete_article'),

    path('school_setup/', views.school_setup, name='school_setup'),
    path('school_setup/add/', views.add_school, name='create_school'),
    path('school_setup/edit/', views.edit_school, name='edit_school'),


    path('school_setup/add_class/', views.add_school_class, name='create_class'),
    path('school_setup/edit_class/<int:id>', views.edit_school_class, name='redact_class'),
    path('school_setup/delete_class/<int:id>', views.delete_school_class, name='delete_class'),

    path('school_setup/add_classmate/<int:id>', views.add_classmate_to_class, name='add_classmate'),
    path('school_setup/edit_child/<int:id>', views.edit_child, name='redact_classmate'),
    path('school_setup/delete_child/<int:id>', views.delete_child, name='delete_classmate'),

    path('school_setup/add_teacher/', views.add_teacher, name='add_teacher'),
    path('school_setup/edit_teacher/<int:id>', views.edit_teacher, name='edit_teacher'),
    path('school_setup/delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),

    path('school_setup/edit_timetable/<int:id>', views.edit_timetable, name='redact_timetable'),

    path('school_setup/add_subject/', views.add_subject, name='add_subject'),

    path('school_setup/edit_subject/<int:id>', views.edit_subject, name='edit_subject'),
    path('school_setup/delete_subject/<int:id>', views.delete_subject, name='delete_subject'),

    #path('school_setup/add_subject_to_day/<int:id>', views.add_subject_to_day, name='add_subject_to_day'),

    path('school_setup/edit_daysubject/<int:id>', views.edit_subject_in_day, name='edit_daysubject'),

    path('my_class', views.my_class, name='my_class'),

    path('teach', views.teach, name="teach_"),
    path('teach/<int:id>/<int:sub>', views.teach_det, name="teach"),

    path('leave_mark/<int:year>/<int:month>/<int:day>/<int:id>/<int:subj>/<int:i>', views.leave_mark, name="leave_mark"),

    path('edit_mark/<int:year>/<int:month>/<int:day>/<int:id>/<int:subj>/<int:i>', views.edit_mark, name="edit_mark"),

    path('teach/edit_hw/<int:id>', views.edit_hw, name="edit_hw"),
    path('teach/delete_hw/<int:id>', views.delete_hw, name="delete_hw")
]

networkjournal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('', include('home.urls')),
    #path('', RedirectView.as_view(url='/child/', permanent=True)),
    #path('home/', RedirectView.as_view(url='/child/', permanent=True)),
]

networkjournal/apps/home/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

from .user_fields import *

class School(models.Model):
    director = models.CharField('username директора', max_length=50)
    name = models.CharField('имя школы', max_length=50)

    site = models.URLField('Сайт', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'школа'
        verbose_name_plural = 'школы'

class Class(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)

    teacher = models.IntegerField('ID классного руководителя')

    num = models.IntegerField('Цифра класса')
    letter = models.CharField('Буква класса', max_length=1)

    def __str__(self):
        return str(self.num) + '\"' + self.letter + '\"'

    class Meta:
        verbose_name = 'школьный класс'
        verbose_name_plural = 'школьные классы'

class Article(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    title = models.CharField('Название статьи', max_length=200)
    text = models.TextField('Текст статьи')
    date = models.DateTimeField('Дата написания', auto_now=True)

    def __str__(self):
        return self.title

    def was_pub_recently(self):
        return self.date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'


class Comment(models.Model):
    test = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.CharField('Автор', max_length=50)
    text = models.CharField('Текст', max_length=200)

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

class SchoolSubject(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)

    subj_name = models.CharField('Название предмета', max_length=100)

    def __str__(self):
        return self.subj_name

    class Meta:
        verbose_name = 'школьный предмет'
        verbose_name_plural = 'школьные предметы'

class Timetable(models.Model):
    schoolClass = models.ForeignKey(Class, on_delete=models.CASCADE)

class DayOfWeek(models.Model):
    timetable = models.ForeignKey(Timetable, on_delete=models.CASCADE)
    dayname = models.CharField('Имя дня', max_length=50)

    def __str__(self):
        return self.dayname

class TimetableSchoolSubject(models.Model):
    dayofweek = models.ForeignKey(DayOfWeek, on_delete=models.CASCADE)
    sublocalid = models.IntegerField('Порядковый номер урока')
    subjSourceId = models.IntegerField('ID школьного предмета')
    teacher = models.IntegerField('ID учителя')
    timeOfStart = models.TimeField('Время начала')
    timeOfEnd = models.TimeField('Время конца')

    def get_subject_model(self):
        return SchoolSubject.objects.get(pk=self.subjSourceId)

    def get_teacher_model(self):
        return User.objects.get(pk=self.teacher)

    def get_teacher_name_and_surname(self):
        return get_user_name(User.objects.get(pk=self.teacher)) + ' ' + get_user_surname(User.objects.get(pk=self.teacher))

    def get_teacher_name_and_surname_brackets(self):
        return '('+get_user_name(User.objects.get(pk=self.teacher)) + ' ' + get_user_surname(User.objects.get(pk=self.teacher))+')'

    def __str__(self):
        return SchoolSubject.objects.get(pk=self.subjSourceId).subj_name

class Mark(models.Model):
    schoolsubject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE)

    mark_value = models.IntegerField('Номинал отметки')

    weekid = models.IntegerField('ID недели в году')

    usrid = models.IntegerField('ID пользователя(ученика)')

    date = models.DateField('data polycheniya')

    def __str__(self):
        return  str(self.mark_value)

class Homework(models.Model):
    schoolClass = models.ForeignKey(Class, on_delete = models.CASCADE)
    subject_id = models.IntegerField('id предмета')
    hwtitle = models.TextField('Название задания')
    hwtext = models.TextField('Текст задания')
    hw_deadline = models.DateField('deadline')
    hw_start = models.DateField('startline')

    def __str__ (self):
        return self.hwtext

    def is_actual(self):
        return  self.hw_deadline >= datetime.date.today() - datetime.timedelta(days=2)

networkjournal/apps/home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from .models import Article, School, Class

class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

networkjournal/templates/child/det.html
{% extends 'child_base.html' %}

{% block title %}{{article.title}} | Новости{% endblock %}
{% block content %}

<div class="container">
	<h2>{{article.title}}</h2>
	<hr>
	<p>{{article.text}}</p>
	<hr>
	<em>Опубликовано {{article.date}}</em>
	<!--<br>
	<br>
	<hr>
	<form action="{% url 'home:leave_comment' article.id %}" method="POST">

		{% csrf_token %}
		<input class="form-control" name="text" required placeholder="Текст комментария"></input>
		<button class="btn btn-info" type="submit" name="button">Оставить комментарий</button>
		<hr>
	</form>
	{% if latest_comm_list %}
	<h4>Комментарии пользователей</h4>
	<hr>
	<div class="container">
		{% for c in latest_comm_list %}
		<h4><strong>{{c.author}}</strong></h4>
		<h6>{{c.text}}</h6>
		<br>
		{% endfor %}
	</div>

	{% else %}
	<h5>Никто ещё не прокомментировал эту новость.</h5>
	{% endif %}-->
</div>
{% endblock %}

networkjournal/templates/child/diary.html
{% extends 'child_base.html' %}

{% block title %}Дневник{% endblock %}
{% block content %}
<div class="container">
	<h1>Сегодня {{date}} ({{weekday}})</h1>
	<a href="#marktable">Перейти к последним полученным оценкам</a>
	<a name="homeworktable"></a>
    <table border="1" class="table text-center">
      <thead>
        <tr>
          <th scope="col" width="150">Предмет</th>
          <th scope="col">Домашнее задание</th>
			<th scope="col" width="200">Крайний срок</th>
        </tr>
      </thead>
      <tbody>
		  {% for subj, dz in dzinfo %}
			<tr>
				<td>{{subj}}</td>
				<td>{{dz}} <!--<a href="https://duckduckgo.com/?q={{dz}}" class="btn btn-info btn-sm" target="_blank">🔍</a>--> </td>
				<td>{{dz.hw_deadline}}{% if date == dz.hw_deadline %}<span style="color: red"><b>(Сегодня!)</b></span>{% endif %}</td>
			</tr>
		  {% endfor %}
      </tbody>
    </table>

	<a name="marktable"></a>
	<a href="#homeworktable">Перейти к домашним заданиям</a>
	<table border="1" class="table text-center">
      <thead>
        <tr>
          <th scope="col" width="150">Предмет</th>
          <th scope="col" width="10">Полученная оценка</th>
			<th scope="col" width="200">Дата получения</th>
        </tr>
      </thead>
      <tbody>
		  {% for subj, mark in markinfo %}
			<tr>
				<td>{{subj}}</td>
				<td style="color:red"><b>{{mark.mark_value}}</b></td>
				<td>{{mark.date}}</td>
			</tr>
		  {% endfor %}
      </tbody>
    </table>
    <br>
    <br>
</div>
{% endblock %}

networkjournal/templates/child/list.html
{% extends 'child_base.html' %}

{% block title %}Главная{% endblock %}
{% block content %}

 {% if article %}
 <div class="container text-center">
	<h4>Новости</h4>
	 {% for a in article %}
  <ul class="list-group mt-4">
  <li class="list-group-item text-left"><strong>{{a.date}}</strong> <span>{{a.title}}</span> <span class="float-right mr-3"><a href="{% url 'home:det' a.id %}">Перейти к новости</a></span></li>
  </ul>
	{% endfor %}

	  </div>
 {% else %}
<div class="container text-center">
	<h1>Школа не разместила ни одной новости.</h1>
</div>
 {% endif %}

</div>
{% endblock %}

networkjournal/templates/child/notifi.html
{% extends 'child_base.html' %}

{% block title %}Уведомления{% endblock %}
{% block content %}
<hr>
<div class="container">
	<strong>Уведомления</strong>
</div>
{% if article %}
{% else %}
{% endif %}

{% endblock %}

networkjournal/templates/child/profile.html
{% extends 'child_base.html' %}

{% block title %}{{profile.name}} {{profile.surName}} | Дневник{% endblock %}
{% block content %}

<div class="container">
	<strong>Профиль</strong>
	<h6>{{profile.name}} {{profile.surName}} {{profile.lastName}}</h6>
	<h3>{{profile.status}}</h3>
</div>
{% endblock %}

networkjournal/templates/child/statistic.html
{% extends 'child_base.html' %}
{% block title %}Статистика{% endblock %}
{% block content %}
<div class="container">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col" width="200">Предмет</th>
          <th scope="col" width="20">Ср. Балл</th>
          <th scope="col">Отметки</th>
        </tr>
      </thead>
      <tbody>
      {% for subj, marks, mid in s_list %}
        <tr>
          <th scope="row">{{subj}}</th>
          <td>{{mid}}</td>
          <td>
              {% for mark in marks %}
                <button type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" data-placement="bottom" title="{{mark.date}}">
                  {{mark}}
                </button>
              {% endfor %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

networkjournal/templates/child/timetable.html
{% extends 'child_base.html' %}
{% block title %}Расписание{% endblock %}
{% block content %}
<div class="container text-center">
  <h1>Расписание для {{class}} класса</h1>
    <p>Сегодня: {{today}} {{time}}</p>
    <a href="#today">Перейти к сегодняшнему дню</a>
    <details>
        <summary>Навигатор</summary>
        {% for d in timetable.dayofweek_set.all %}
        <a href="#{{d.dayname}}">{{d.dayname}}</a>
        <br>
        {% endfor %}
    </details>
  {% for d in timetable.dayofweek_set.all %}
    <a name="{{d.dayname}}"></a>
    {% if today == d.dayname %}
    <a name="today"></a>
    {% endif %}
    <table class="table">
        <caption>{{d.dayname}}</caption>
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Предмет</th>
          <th scope="col">Преподаватель</th>
          <th scope="col">Время начала</th>
          <th scope="col">Время конца</th>
        </tr>
      </thead>
      <tbody>
        {% for subj in d.timetableschoolsubject_set.all %}
        <tr {% if today == d.dayname and time > subj.timeOfStart and time < subj.timeOfEnd %}class="table-active"{% endif %}>
          <th scope="row">{{subj.sublocalid}}</th>
          <td scope="row">{{subj.get_subject_model}}</td>
          <td scope="row">{{subj.get_teacher_model}} {{subj.get_teacher_name_and_surname_brackets}}</td>
          <td scope="row">{{subj.timeOfStart}}</td>
          <td scope="row">{{subj.timeOfEnd}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br>
    <br>
  {% endfor %}
</div>
{% endblock %}

networkjournal/templates/child/tips.html
{% extends 'child_base.html' %}

{% block title %}Заметки{% endblock %}
{% block content %}

{% if tips_list %}
<h4>Заметки</h4>
<hr>
<div class="container">
	{% for е in tips_list %}
	<h5>{{e.text}}</h5>
	<h6><em>{{e.text}}</em></h6>
	<br>
	{% endfor %}
</div>
{% else %}
<h4>Вы ещё не добавляли заметок.</h4>
{% endif %}

<div class="container">
	<form action="{% url 'home:add_tip' {{request.user}} %}" method="POST">
		{% csrf_token %}
		<input class="form-control" name="text" required placeholder="Текст заметки"></input><button class="btn btn-info" type="submit" name="button">Добавить заметку</button>
		<hr>
	</form>
</div>
{% endblock %}